labs13-handy-app/Frontend

- netlify.toml
> Build folder created and netlify.toml file added

- handyapp/src/Callback/Callback.js
- handyapp/src/Landing.js
- handyapp/src/actions/getToken.js
- handyapp/src/auth/Auth.js
- handyapp/src/utils/AxiosAuth.js
> User scope added on token to be retrieved by the backend

- handyapp/package.json
- handyapp/src/components/Home.js
- handyapp/src/components/MyForm.js
- handyapp/src/reducers/index.js
- handyapp/src/routes.js
- handyapp/yarn.lock
- [ X] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ X] Complete, tested, ready to review and merge
- [X ] My code has been reviewed by at least one peer
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] My changes generate no new warnings
- [ X] There are no merge conflicts
> Home Component Form

- handyapp/src/components/MyForm.js
> Spencer meredith

- handyapp/src/actions/getToken.js
- handyapp/src/components/Auth/Auth.js
- handyapp/src/history.js
> fixing token bug

- handyapp/src/actions/getToken.js
> getToken to Heroku backend

- handyapp/src/App.js
> removed merge conflict code

- handyapp/src/components/ServiceProviders/Bid.js
> bid component  fixing names

- handyapp/src/App.js
- handyapp/src/actions/getToken.js
- handyapp/src/components/Auth/Auth.js
- handyapp/src/components/Auth/auth0-variables.js
- handyapp/src/components/Callback/Callback.js
- handyapp/src/components/Dashboard/Dashboard.js
- handyapp/src/components/HomePage/ContractorForm.js
- handyapp/src/components/HomePage/Home.js
- handyapp/src/components/HomePage/HomeownerForm.js
- handyapp/src/components/Landing.js
- handyapp/src/components/NavBar.js
- handyapp/src/components/Onboarding/Onboarding.js
- handyapp/yarn.lock
Redirect User from onboarding if onboarding completed, fixed account type rendering issue, redirect to dashboard component.
> Redirect User from onboarding if onboarding completed, fixed account type rendering issue, redirect to dashboard component

- handyapp/src/components/Auth/Auth.js
> Fixed hang request bug

- handyapp/src/components/Auth/Auth.js
fixed bug in Auth contructor class
> fixed bug in Auth contructor class

- handyapp/public/index.html
merge conflict on index.html resolved
> merge conflict on index.html resolved

- handyapp/src/App.js
- handyapp/src/actions/getToken.js
- handyapp/src/components/Auth/Auth.js
- handyapp/src/components/Auth/auth0-variables.js
- handyapp/src/components/Dashboard/Dashboard.js
- handyapp/src/components/NavBar.js
- handyapp/src/components/UserCard/UserCard.js
- handyapp/yarn.lock
Working on fixing Navbar issues.
- [x ] Test A
> Guillaume savy

- handyapp/src/actions/getToken.js
- handyapp/src/components/Auth/Auth.js
- handyapp/src/components/Auth/auth0-variables.js
> changed to production url

- handyapp/package.json
- handyapp/yarn.lock
> yarn lock file cleaned up

- handyapp/src/App.js
There was an unresolved merge conflict on the master branch of app.js causing it to not be able to open on local host. I resolved the conflict
> resolved error on app.js

- handyapp/src/components/Projects/BidsForProject.js
- handyapp/src/components/Projects/ProjectsById.js
Added things to the two components related to getting projects by id, to reflect the new fields available
> Refactored project by id to reflect new endpoint and schema

- handyapp/src/actions/getUserProjects.js
> Changed getuserprojects to prod url

- handyapp/src/components/HomeOwners/AddFeedbackForm.js
- handyapp/src/components/HomeOwners/ServiceProviderFeedback.js
Created a form to add feedback to a service provider. It's not styled but it works.
> created unstyled working form to post new feedback

- handyapp/package.json
- handyapp/public/index.html
- handyapp/src/App.js
- handyapp/src/components/Projects/BidsForProject.js
- handyapp/src/components/Projects/Project.js
- handyapp/src/components/Stripe/CheckoutForm.js
- handyapp/src/components/Stripe/Stripe.js
Configured basic Card element for stripe with test API key, that doesn't post anywhere yet. 
> adding foundation for stripe element

- handyapp/src/components/AddProject/AddProject.css
- handyapp/src/components/AddProject/AddProject.js
addProject without pictures handled.
> addProject without pictures handled

- handyapp/yarn.lock
> bid component ui visual done functionally time

- handyapp/src/components/Projects/BidsForProject.js
- handyapp/src/components/Projects/ProjectsById.css
- handyapp/src/components/Projects/ProjectsById.js
Added styles for the get projects by id and bidsbyproject components
> changed styles for project by id, and bids

- handyapp/src/components/Projects/Projects.js
> Removed console.log bug

- handyapp/src/components/Auth/Auth.js
- handyapp/src/components/Projects/Projects.js
> Fixing bug on Login.

- handyapp/src/components/Projects/Projects.js
> working on fixing project listing bug

- handyapp/src/components/LandingPage/Landing.js
- handyapp/src/components/Projects/Projects.js
> fixing projects bug

- handyapp/src/components/AddProject/AddProject.js
- handyapp/src/components/Projects/Projects.js
> Changed Addproject url to production url

- handyapp/package.json
- handyapp/src/components/HomePage/HomeownerForm.js
- handyapp/yarn.lock
> working on style for homewonerform with matria; styles

- handyapp/src/App.js
- handyapp/src/components/ServiceProviders/AddNewBid.js
- handyapp/src/components/ServiceProviders/SubmitBid.css
- handyapp/src/components/ServiceProviders/SubmitBid.js
Created components and form to be able to add a bid, need to get token in production to test. 
> working on adding bid

- handyapp/src/components/ServiceProviders/AddNewBid.js
- handyapp/src/components/ServiceProviders/SubmitBid.js
Trying to fix getting user id from token action on submit bid component
> bug fix for add bid

- handyapp/src/components/ServiceProviders/SubmitBid.js
adds console logs to debug component in production environment
> adding console logs to debug in production

- handyapp/src/components/ServiceProviders/SubmitBid.js
fixed issue in reducer
- [z] Bug fix (non-breaking change which fixes an issue)
> fixed bug in reducer

- handyapp/src/actions/addBid.js
- handyapp/src/components/ServiceProviders/AddNewBid.js
> configured ablity to add bids on projects

- handyapp/src/components/ServiceProviders/AddNewBid.js
- handyapp/src/components/ServiceProviders/SubmitBid.css
> styled form

- handyapp/src/components/ServiceProviders/AddNewBid.js
- handyapp/src/components/ServiceProviders/SubmitBid.css
Had to add class names, css file interfered with other components.
> working on styles and responsivness

- handyapp/src/components/ServiceProviders/AddNewBid.js
Changed around state on new bid component
> new bid stopped working trying to fix

- handyapp/src/components/ServiceProviders/AddNewBid.js
- handyapp/src/components/ServiceProviders/SubmitBid.js
Configues the ablity to add a bid without manually inputting user id or project id.
> add bid works

- handyapp/package.json
- handyapp/src/components/AddProject/AddProject.js
- handyapp/src/components/HomeOwners/AddFeedbackForm.js
- handyapp/src/components/HomeOwners/FeedbackFormM.js
- handyapp/src/components/HomeOwners/ServiceProviderFeedback.js
- handyapp/yarn.lock
> Uncommented form

- handyapp/src/components/HomePage/HomeownerForm.js
there were two default exports in the Homeowner form page, causing the builds to fail so the current master couldn't be deployed, i commented one out for the time being 
> fixing error so master can be deployed

- handyapp/src/components/Projects/Project.js
- handyapp/src/components/Projects/Projects.js
- handyapp/src/components/Projects/UserProject.js
- handyapp/src/components/UserProjects/UserProjects.js
Creates Links to help establish user flow
> added links to update user flow

- handyapp/package.json
- handyapp/src/components/Stripe/CheckoutForm.js
> foundations of stripe-checkout

- handyapp/src/components/HomePage/HomeownerForm.js
> added imports working on homeownerform styles looks ui

- handyapp/src/components/HomePage/HomeownerForm.js
> setup formating fixed issues for material ui

- handyapp/src/components/Projects/BidsForProject.js
- handyapp/src/components/Stripe/Stripe.js
Passing the amount of the bid as a prop to checkout.
> able to pass in amount based on bid for stripe checkout

- handyapp/src/App.js
- handyapp/src/components/NotFound/NotFound.js
- handyapp/yarn.lock
> Set up 404 page

- handyapp/src/App.js
- handyapp/src/components/NotFound/NotFound.js
Path of the NotFound rote
Created a button with a link on it to redirect the user back to the homepage
> Created a button with a link on it to redirect the user back to the homepage

- handyapp/src/App.js
- handyapp/src/components/Stripe/CheckoutForm.js
> Url changed

- handyapp/src/App.js
> container class added to div in App component

- handyapp/src/components/HomePage/ContractorForm.js
- handyapp/src/components/HomePage/HomeownerForm.js
- handyapp/src/components/LandingPage/Landing.js
> user account type set to localstrorage to help with routing

- handyapp/src/components/Stripe/CheckoutForm.js
Changed component for stripe checkout back to dynamically rendering price of bid
> changed front end amount back to being dynamic

- handyapp/src/components/Auth/Auth.js
- handyapp/src/components/ContractorDashboard/ContractorDashboard.js
- handyapp/src/components/HomeOwnerDashboard/HomeOwnerDashboard.js
> Fixing routing issues by setting user account_type in localStorage.

- handyapp/src/components/ContractorDashboard/ContractorDashboard.js
- handyapp/src/components/HomeOwnerDashboard/HomeOwnerDashboard.js
> fixing bug

- handyapp/src/components/ContractorDashboard/ContractorDashboard.js
- handyapp/src/components/HomeOwnerDashboard/HomeOwnerDashboard.js
> fixing bug on deploy

- handyapp/src/App.js
- handyapp/src/components/ContractorDashboard/ContractorDashboard.js
- handyapp/src/components/HomeOwnerDashboard/HomeOwnerDashboard.js
> working on routing issues

- handyapp/src/components/ContractorCard/ContractorCard.js
adds the ablity for a contractor to set up an account to take payment
[x] New feature (non-breaking change which adds functionality)
> stripe connect callback added to contractor dashboard

- handyapp/src/components/Onboarding/Onboarding.js
> Working on fixing routing bugs

- handyapp/src/components/HomePage/ContractorForm.js
- handyapp/src/components/HomePage/HomeownerForm.js
> HomeownerForm and ContractorForm modified

- handyapp/src/components/ContractorCard/ContractorCard.js
> contractorCard modified to change profile picture

- handyapp/.gitignore
- handyapp/src/App.js
- handyapp/src/actions/addBid.js
- handyapp/src/actions/addFeedback.js
- handyapp/src/actions/addProfilePic.js
- handyapp/src/actions/addProject.js
- handyapp/src/actions/addProjectPics.js
- handyapp/src/actions/deleteProject.js
- handyapp/src/actions/editProject.js
- handyapp/src/actions/getBids.js
- handyapp/src/actions/getFeedbackByContractorId.js
- handyapp/src/actions/getProjectById.js
- handyapp/src/actions/getProjectImages.js
- handyapp/src/actions/getProjects.js
- handyapp/src/actions/getToken.js
- handyapp/src/actions/getUser.js
- handyapp/src/actions/getUserProjects.js
- handyapp/src/actions/onBoarding.js
- handyapp/src/actions/paymentConnection.js
- handyapp/src/components/AddProject/AddProject.js
- handyapp/src/components/Auth/Auth.js
- handyapp/src/components/Auth/auth0-variables.js
- handyapp/src/components/ContractorCard/ContractorCard.js
- handyapp/src/components/HomePage/ContractorForm.js
- handyapp/src/components/HomePage/HomeownerForm.js
- handyapp/src/components/Stripe/CheckoutForm.js
- handyapp/src/components/Stripe/MakePayment.js
- handyapp/src/components/UserCard/UserCard.js
> Environment variables setup

- handyapp/src/App.js
- handyapp/src/actions/paymentConnection.js
- handyapp/src/components/Callback/StripeCallback.js
> Tyler foreman

- handyapp/src/components/HomePage/ContractorForm.js
- handyapp/src/components/Onboarding/Onboarding.js
contractor onboarding bug fixed
> contractor onboarding bug fixed

- handyapp/package.json
- handyapp/yarn.lock
Needs Fixing of Domain Error: domain option is required
> resolving conflict when starting the app

- handyapp/src/components/HomePage/HomeownerForm.js
> first name text form

- handyapp/src/components/EditProfile/EditProfile.js
> Edit profile done

- handyapp/src/components/ContractorCard/ContractorCard.js
- handyapp/src/components/HomePage/HomeownerForm.js
Fixed error on homeowner and contractor dashboards
> Fixed error on dashboards

- handyapp/src/components/ContractorDashboard/ContractorDashboard.js
- handyapp/src/components/HomePage/ContractorForm.js
> Fixed routing error

- handyapp/src/components/EditProfile/EditProfile.js
> Refactored Edit profile form

- handyapp/src/components/ContractorDashboard/ContractorDashboard.js
> merge conflict resolved

- handyapp/package.json
- handyapp/src/components/AddProject/AddProject.css
- handyapp/src/components/ContractorDashboard/ContractorDashboard.js
- handyapp/src/components/Projects/UserProject.css
- handyapp/src/components/Projects/UserProject.js
- handyapp/yarn.lock
> Carousel on project done

- handyapp/src/components/ContractorCard/ContractorCard.css
- handyapp/src/components/ContractorCard/ContractorCard.js
- handyapp/src/components/ContractorDashboard/ContractorDashboard.js
- handyapp/src/components/EditProfile/EditProfile.js
- handyapp/src/components/HomePage/ContractorForm.js
- handyapp/src/components/Onboarding/Onboarding.js
- handyapp/src/components/Projects/Projects.js
- handyapp/src/components/Projects/ProjectsById.css
Images array added to projects on getProjects
> Images array added to projects on getProjects

- handyapp/src/components/Projects/Project.css
- handyapp/src/components/Projects/Project.js
> contractor projectList style done

- handyapp/package.json
- handyapp/src/components/Projects/Project.css
- handyapp/src/components/Projects/Project.js
- handyapp/src/components/Projects/Projects.js
- handyapp/src/components/Projects/UserProject.css
- handyapp/src/components/Projects/UserProject.js
- handyapp/yarn.lock
> View more overlay added to project

- handyapp/src/components/AddProject/AddProject.js
- handyapp/src/components/HomeOwners/FeedbackFormM.js
- handyapp/src/components/HomePage/ContractorForm.js
- handyapp/src/components/HomePage/HomeownerForm.js
- handyapp/src/components/LandingPageN/components/NavigationBar.js
- handyapp/src/components/LandingPageN/components/Section1.js
- handyapp/src/components/LandingPageN/components/Section2.js
- handyapp/src/components/Onboarding/Onboarding.js
> Styled Components

- handyapp/src/components/AddProject/AddProject.js
> bug on add project fixed

- handyapp/yarn.lock
> fixed yarn lock error

- handyapp/src/components/Onboarding/Onboarding.js
- handyapp/src/components/Projects/Project.js
- handyapp/src/components/Projects/Projects.js
> Category added to project component

- handyapp/src/components/Projects/Project.css
- handyapp/src/components/Projects/Project.js
>  styled categories on Project component

- handyapp/src/components/Auth/Auth.js
> Clear localStorage on logout added

- handyapp/src/components/HomePage/ContractorForm.js
- handyapp/src/components/Onboarding/Onboarding.css
> Homeowner form bug fixed

- handyapp/src/App.js
- handyapp/src/components/Footer/Footer.js
> Making footer for all pages

- handyapp/src/components/Projects/BidsForProject.js
made the card that lists bids display the price for the given bid
> addded price to bid card

- handyapp/src/components/AddProject/AddProject.js
- handyapp/src/components/HomePage/ContractorForm.js
- handyapp/src/components/HomePage/HomeownerForm.js
- handyapp/src/components/LandingPageN/components/Header.js
- handyapp/src/components/ServiceProviders/AddNewBid.js
Button styles
Made few tweaks on styling
> Made few tweaks on styling

- handyapp/src/App.js
> fixing footer

- handyapp/src/components/Projects/Projects.js
Available projects on contractor dashboard filtered based on contractor skill.
> Available projects on contractor dashboard filtered based on contractor skill.

- handyapp/src/components/Footer/Footer.js
> fixed big spacing

- handyapp/src/App.js
- handyapp/src/components/ContractorDashboard/ContractorDashboard.js
- handyapp/src/components/ContractorEditProfile/ContractorEditProfile.css
- handyapp/src/components/ContractorEditProfile/ContractorEditProfile.js
- handyapp/src/components/HomeOwnerDashboard/HomeOwnerDashboard.js
Edit profile for contractor done
> Edit profile for contractor done

- handyapp/src/actions/deleteBid.js
- handyapp/src/components/HomeOwners/FeedbackFormM.js
- handyapp/src/components/Projects/BidsForProject.js
- handyapp/src/components/ServiceProviders/AddNewBid.js
fixed bugs when adding a bid, and when deleting a bid
> bugs fixed in add bid and delete bid components

- handyapp/src/App.js
- handyapp/src/components/ContractorEditProfile/ContractorEditProfile.css
- handyapp/src/components/ContractorEditProfile/ContractorEditProfile.js
Fixed footer bug and modified contractor edit profile form
> Fixed footer bug and modified contractor edit profile form

- handyapp/src/components/Footer/Footer.js
> fixing text and links

- handyapp/src/components/AddProject/AddProject.css
- handyapp/src/components/Auth/Auth.js
- handyapp/src/index.css
> Font fixed

- handyapp/src/App.js
> merge conflict removed

- handyapp/src/App.js
> fixed react-router-modal bug

- handyapp/src/App.js
- handyapp/src/components/ContractorDashboard/ContractorDashboard.js
- handyapp/src/components/Projects/Project.js
- handyapp/src/components/Projects/Projects.js
- handyapp/src/components/ServiceProviders/AddNewBid.js
> Fixed React router modal rendering issue

- handyapp/src/components/Callback/StripeCallback.js
- handyapp/src/components/ContractorCard/ContractorCard.js
- handyapp/src/components/Footer/Footer.js
- handyapp/src/components/Stripe/Transfer.js
conditionally renders buttons on contractor card based on payment id, gives alerts to contractor.
> Configuring stripe connect buttons on contractor card

- handyapp/src/components/ContractorDashboard/ContractorDashboard.js
> Contractor dashboard rerouting

- handyapp/src/App.css
- handyapp/src/components/AddProject/AddProject.css
- handyapp/src/components/Auth/Auth.js
- handyapp/src/components/EditProfile/EditProfile.css
- handyapp/src/components/HomeOwnerDashboard/HomeOwnerDashboard.css
- handyapp/src/components/HomePage/ContractorForm.js
- handyapp/src/components/Onboarding/Onboarding.js
- handyapp/src/components/Projects/UserProject.css
- handyapp/src/components/UserCard/UserCard.css
- handyapp/src/components/UserProjects/UserProjects.css
> Fixed userID bug on login new users

- handyapp/src/components/EditProfile/EditProfile.css
- handyapp/src/components/HomeOwnerDashboard/HomeOwnerDashboard.css
- handyapp/src/components/Projects/UserProject.css
- handyapp/src/components/UserCard/UserCard.css
- handyapp/src/components/UserCard/UserCard.js
- handyapp/src/components/UserProjects/UserProjects.css
Homeowner dashboard responsive
> Homeowner dashboard responsive

- handyapp/src/components/HomeOwners/FeedbackFormM.js
- handyapp/src/components/HomeOwners/ServiceProviderFeedback.js
- handyapp/src/components/Projects/ProjectsById.js
- handyapp/src/components/Stripe/Transfer.js
Cleaning up the overall user flow to make it look better, git rid of things that don't need to be there. 
> cleaning up user flow

- handyapp/src/components/AddProject/AddProject.js
> Select added to addproject component

- handyapp/package.json
- handyapp/src/App.js
- handyapp/src/components/HomeOwners/AddFeedbackForm.js
- handyapp/src/components/HomeOwners/Feedback.js
- handyapp/src/components/HomeOwners/FeedbackFormM.js
- handyapp/src/components/HomeOwners/ServiceProviderFeedback.js
- handyapp/yarn.lock
> Feedback stars rating done

- handyapp/src/components/HomeOwners/Feedback.css
- handyapp/src/components/HomeOwners/Feedback.js
> Feedback component restyled

- handyapp/src/components/ContractorCard/ContractorCard.css
- handyapp/src/components/HomeOwners/ServiceProviderFeedback.css
- handyapp/src/components/HomeOwners/ServiceProviderFeedback.js
- handyapp/src/components/LandingPageN/components/NavigationBar.js
> Contractor info component styled

- handyapp/src/components/HomeOwners/ServiceProviderFeedback.css
> contractor profile component responsive

- handyapp/src/components/HomeOwners/ServiceProviderFeedback.css
- handyapp/src/components/HomeOwners/ServiceProviderFeedback.js
- handyapp/src/components/Projects/BidForProject.css
- handyapp/src/components/Projects/BidsForProject.js
- handyapp/src/components/Projects/ProjectsById.js
> BidForProject component styled

- handyapp/src/components/ContractorCard/ContractorCard.css
- handyapp/src/components/ContractorCard/ContractorCard.js
- handyapp/src/components/UserCard/UserCard.css
> contractor dashboard responsive

- handyapp/src/App.js
removes footer as it's not displaying right
> removed footer

- handyapp/src/App.js
- handyapp/src/components/LandingPageN/LandingPage.js
- handyapp/src/components/LandingPageN/components/Header.js
> Login added to get started button

- handyapp/src/components/Projects/BidsForProject.js
- handyapp/src/components/Projects/Project.js
- handyapp/src/components/Projects/ProjectsById.js
- handyapp/src/components/Stripe/CheckoutForm.js
Fixed buttons and card on BidsForProject component
> Fixed buttons and card on BidsForProject component
